### PR TITLE
c++ program to check leap year

### PR DESCRIPTION
**Pull request by Hics0000**

### CODE REVIEW

**Comment by tb-rules10** [comment]
I won't merge this pr but it will count towards hacktoberfest as I have added the label

**Comment by Hics0000** [comment]
will it will count in my hacktoberfest contest

**Comment by tb-rules10** [comment]
yes it will

**Comment by Hics0000** [comment]
My four PR is accepted and got tag of HACTOBERFEST FEST ACCEPTED.
Is there is chance to win the goodies.
Or I have to do some extra work.
please guide me I am clueless, It is my first time
Please check this attachment ,It is of my hacktoberfest account
Screenshot (55)

**Comment by tb-rules10** [comment]
You have to wait for 14 days  of review period, some of your pr's might get rejected during that time.
I'll suggest you making few more pr's till then

**Comment by tb-rules10** [comment]
At the end of 14days if 4 pr's of yours get passed then you'll surely get hacktoberfest swags

**Comment by sohampod** [comment]
hey is there any cpp program i can add to make it into the hacktoberfest?

**Comment by tb-rules10** [comment]
this repo is only for hello world programs
you can add any good cpp program to my 2nd repo for hacktoberfest
https://github.com/tb-rules10/Algorithm

**Pull request closed without merging**
